### ISSUE TITLE
I got error 403. What am i doing wrong?

### ISSUE THREAD

**Issue by Szafranek13** [PlaceCZ/Bot#21]
![bildo](https://user-images.githubusercontent.com/53099243/161443209-415c1dff-760f-4fc6-b8c6-855673940b02.png)
System is Linux, using `node headlessBot.js autologin` command.
My logins.txt file:

**Comment by wereii** [comment]
I have deleted the logins screenshot because it shares your internal reddit tokens on public internet and someone might misuse it.

**Comment by wereii** [comment]
The server was restarted recently, it might be because of that.

**Comment by Szafranek13** [comment]
Yeah, now works. Thanks :D
